var affdata={
  gongInfo:[
    {label:"小区名称",value:"WLMQ_XBL0_西城康居苑南(800M)D_CSCPI_SGT2C_2"},
    {label:"区县",value:"西北路分局"},
    {label:"支局",value:"红庙子城区"},
    {label:"ENBID",value:"1043985"},
    {label:"CELLID",value:"18"},
    {label:"城市/农村",value:"城市"},
  ],
  xingInfo:[
    {label:"连接成功率",value:"94.50%"},
    {label:"掉线率",value:"5.50%"},
    {label:"优良率",value:"99.60%"},
    {label:"覆盖率",value:"94.45%"}
  ],
  zhiInfo:[
    {label:"重定向比例",value:"0"},
    {label:"CQI优良比",value:"92.26%"},
    {label:"是否异常",value:"否"},
    {label:"异常发生时间",value:"————"},
    {label:"异常类型",value:"————"},
    {label:"是否故障",value:"否"}
  ],
  fuInfo:[
    {label:"是否高负荷小区",value:"否"},
    {label:"是否超闲小区",value:"是"},
    {label:"最大RRC连接用户数",value:"1"},
    {label:"上行PRB平均占用率：",value:"0.101%"},
    {label:"下行PRB平均占用率",value:"0.031%"},
    {label:"prb利用率(7*24小时最大值)",value:"3.52%"},
  ]
}
export {affdata}